// Mocks generated by Mockito 5.4.6 from annotations
// in pubchem/test/app/data/repositories/compound_search_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pubchem/app/data/datasources/local/preference/pref_manager.dart'
    as _i8;
import 'package:pubchem/app/data/datasources/remote/pubchem/model/pubchem_cid_response.dart'
    as _i3;
import 'package:pubchem/app/data/datasources/remote/pubchem/model/pubchem_compound_details_response.dart'
    as _i4;
import 'package:pubchem/app/data/datasources/remote/pubchem/model/pubchem_description_response.dart'
    as _i5;
import 'package:pubchem/app/data/datasources/remote/pubchem/model/pubchem_property_response.dart'
    as _i2;
import 'package:pubchem/app/data/datasources/remote/pubchem/pubchem_remote_source.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePubChemPropertyResponse_0 extends _i1.SmartFake
    implements _i2.PubChemPropertyResponse {
  _FakePubChemPropertyResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePubChemCidResponse_1 extends _i1.SmartFake
    implements _i3.PubChemCidResponse {
  _FakePubChemCidResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePubChemCompoundDetailsResponse_2 extends _i1.SmartFake
    implements _i4.PubChemCompoundDetailsResponse {
  _FakePubChemCompoundDetailsResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePubChemDescriptionResponse_3 extends _i1.SmartFake
    implements _i5.PubChemDescriptionResponse {
  _FakePubChemDescriptionResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PubChemRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPubChemRemoteSource extends _i1.Mock
    implements _i6.PubChemRemoteSource {
  MockPubChemRemoteSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.PubChemPropertyResponse> getCompoundProperties(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompoundProperties,
          [name],
        ),
        returnValue: _i7.Future<_i2.PubChemPropertyResponse>.value(
            _FakePubChemPropertyResponse_0(
          this,
          Invocation.method(
            #getCompoundProperties,
            [name],
          ),
        )),
      ) as _i7.Future<_i2.PubChemPropertyResponse>);

  @override
  _i7.Future<_i3.PubChemCidResponse> getCompoundCids(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompoundCids,
          [name],
        ),
        returnValue:
            _i7.Future<_i3.PubChemCidResponse>.value(_FakePubChemCidResponse_1(
          this,
          Invocation.method(
            #getCompoundCids,
            [name],
          ),
        )),
      ) as _i7.Future<_i3.PubChemCidResponse>);

  @override
  _i7.Future<_i4.PubChemCompoundDetailsResponse> getCompoundDetailsByCid(
          int? cid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompoundDetailsByCid,
          [cid],
        ),
        returnValue: _i7.Future<_i4.PubChemCompoundDetailsResponse>.value(
            _FakePubChemCompoundDetailsResponse_2(
          this,
          Invocation.method(
            #getCompoundDetailsByCid,
            [cid],
          ),
        )),
      ) as _i7.Future<_i4.PubChemCompoundDetailsResponse>);

  @override
  _i7.Future<_i5.PubChemDescriptionResponse> getCompoundDescription(int? cid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompoundDescription,
          [cid],
        ),
        returnValue: _i7.Future<_i5.PubChemDescriptionResponse>.value(
            _FakePubChemDescriptionResponse_3(
          this,
          Invocation.method(
            #getCompoundDescription,
            [cid],
          ),
        )),
      ) as _i7.Future<_i5.PubChemDescriptionResponse>);
}

/// A class which mocks [PrefManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrefManager<T> extends _i1.Mock implements _i8.PrefManager<T> {
  MockPrefManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> setString(
    String? key,
    T? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> getString(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getString,
          [key],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);
}
